### PR TITLE
Synology Docker-Compose

### PR DESCRIPTION
**Pull request by jpartain89**
I decided to add my `docker-compose.yml` file that works on my Synology DS918+, complete with `.env` editable file for portability.

### CODE REVIEW

**Comment by davidnewhall** [comment]
Wow, very cool. I'll check this out a bit more later today and merge it up. Ultimately I'll move your README into the wiki and reduce the README to a wiki link, but we can put it here for now.

Thank you!

**Comment by davidnewhall** [comment]
@scyto - If you have a minute, please share your feedback.

**Comment by davidnewhall** [comment]
been super busy at work, will get to this soon!

**Comment by scyto** [comment]
Was there something you wanted me to focus on?

**Comment by davidnewhall** [comment]
Nothing specific. Just give it a look, read the doc, leave any comments or questions. If you can test it, that's a bonus!

**Comment by scyto** [comment]
testing now, having issues - partly because the instruction are confusing to anyone who hasn't used compose
(believe it or not while i have used yaml files in stacks for swarms i had never bothered with compose); i think we can make some simple changes for clarity - but i need to collect my thoughts on those (and i don't have my primary dev machine running its mobo failed so not sure i want to mess around with git on this machine).

Stuck here, for the life of me can't figure out the issue - the network is defined in the .env file - i assume i don't have to pre-create the network....? otherwise there is not much point... maybe i will try one of my existing networks..

```
WARNING: Some networks were defined but are not used by any service: ${GRAFANA_NETWORK}
ERROR: Service "influxdb" uses an undefined network "Grafana_Net"
alexb@SYN01:/volume1/docker/unifi-poller$

**Comment by scyto** [comment]
It seems that the variable `${GRAFANA_NETWORK}` isn't being expanded in the `networks:` directive section of compose file, I have no idea why.

**Comment by scyto** [comment]
Ok this constitutes my review, i am using 'the eyes' of this being someone trying their first compose (i.e. they have mostly used synology UI or portainer or the like).

Overall, awesome job @jpartain89 you have made me like yaml files and actually bother with docker-compose, nicely constructed, nicely formatted - couple of tech issues and I think we need to get the docs a little clearer in places.  I have no clue not to lint the files in github and my machine with gitdesktop and vscode is down so apologies if this is the wrong wat.

**readme.md**

- get rid of the clever mkdir using braces - you can just put the two mkdir command sequentially, that will use less doc space, you will not have to explain braces and all, and not make me go figure out WTF the braces were doing - i assumed it was some weird expansion of variables but it is rather just clever shell stuff - cute but confusing - also no reason for them not to make those folders in the UI at the same time as master folder
- consider calling the top level folder unifi-poller not grafana in the example - for a second there I was a little confused what was going where
- explain that the .env file should be called just that (maybe tell them not to rename the compose file either lol)
- tell them to use sudo docker-compose up - seems docker compose is less than helpful if that is forgotten
- why when i run sudo docker compose up does the process not return me to shell?  I can control+c which stop the containers and the do sudo docker-compose start - which does what i want - instruction feel lacking here
- consider using the PID number from my page for consistency - good doc habit
- was i supposed to do something to create the unifi db on influx - I expected that to happen for me, if not is there a way we can inject that into the running container as a command using s script we keep in this repo?

**docker-compose.yml**
for me the expansion of ${GRAFANA_NETWORK} isn't working in the network directive section, if i hard code it to match whats in the ,env file it works - i am unclear what the issue is

**.env**
- nice, first time i have seen something that makes me thing yaml files are useful, well done convincing me :-) (i had been using them for stacks).
- the unifi URL is invalid for unifiOS i think - i removed the 8443, aka mine is UNIFI_URL=https://192.168.1.1 - at least mention this in readme.md

**Comment by jpartain89** [comment]
I'm currently at work right now, so I can't give an elaborate response till later, but thanks for the extensive review!

I'll make sure to hop in there and update accordingly, once I'm able to really look at everything you've suggested.

But, as for the

>     * why when i run sudo docker compose up does the process not return me to shell?  I can control+c which stop the containers and the do sudo docker-compose start - which does what i want - instruction feel lacking here

I apologize for being massively lacking in all of the proper info! `sudo docker-compose up -d` is required. The `-d` is what tells the command line to allow the return to shell after the creation of the containers.

And as for the `Networks:` directive, since its a `key:` and not a `:value` in that dictionary is why it wont expand. I think they have it where only the `:value` side expands. That way the `key:` has a set value for the dictionary. 

I'll for sure get to the rest of it in a bit. Just wanted to get those out. 

Thanks for the awesome feedback!

**Comment by scyto** [comment]
thanks (and of course my comments come from someone lacking in knowledge of compose)
-d for detach make sense, shame docker-compose --help doesn't list that arg - sigh, thanks docker

**Comment by davidnewhall** [comment]
Thank you guys! I'm most interested in correct technical steps (which I can't easily test myself without one of these devices), so I really appreciate y'all doing that for me. I'm pretty good at writing technical documentation and will undoubtedly re-write a lot of what you've given just based on my own style preferences, but I will make sure the "tech command thingies" stay the same. As I mentioned before, I will ultimately move this documentation into the wiki and change this README to a pointer there, but we can certainly get it all shiny in this PR before I do that. I'll even merge this before I move it to the wiki later because I've been exceedingly busy with other things lately.

On a lighter note:
I smiled while reading about your struggles with the curly braces. As someone who's been bashing for 25 years, that stuff is second nature and I forget many folks don't understand the shell as well as others. I do agree that listing `mkdir` in there twice is a great alternative to avoid confusion from shell-newcomers. It also avoids mistakes from folks not running a shell that understands what curly braces are (looking at you `zsh`).

Great work gentlemen!

**Comment by scyto** [comment]
@jpartain89  much nicer on the docs
i noticed this typo:
image

and you should put a note about the URL being different for unifios without the 8443 or you will get lots of noobs opening issues (unless UI also made unifi OS listen on 8443 and and I missed that memo?) - aka this is for UDM / UDMP customers.

image

Lastly this would still break in my environment.  I found no workaround but to hardcode... is there something i am doing wrong?

image

**Comment by scyto** [comment]
oh and BTW, out of interest, what are these for? 
image

**Comment by davidnewhall** [comment]
Most folks wont have a rendering callback url, and if they do, they should know how to set it up. I'd recommend removing those settings. The server domain setting is generally "fine" at the default and that should only need to be set in a custom configuration (where someone proxies through nginx, etc). These variables shouldn't be exposed by default. They can be there, but should be commented out.

**Comment by scyto** [comment]
> Most folks wont have a rendering callback url, and if they do, they should know how to set it up. I'd recommend removing those settings. The server domain setting is generally "fine" at the default and that should only need to be set in a custom configuration (where someone proxies through nginx, etc). These variables shouldn't be exposed by default. They can be there, but should be commented out.

I agree.

**Comment by jpartain89** [comment]
Hey guys! Thanks for all the feedback and suggestions. I'm working through them right now.

But, for the first issue: [the UnifiOS port number](https://help.ui.com/hc/en-us/articles/218506997)

@scyto:  
> and you should put a note about the URL being different for unifios without the 8443 or you will get lots of noobs opening issues (unless UI also made unifi OS listen on 8443 and and I missed that memo?) - aka this is for UDM / UDMP customers.
> 
> image

That page does show `8443` is the correct port for every Unifi management service.

Screen Shot 2020-08-17 at 3 37 10 AM
Screen Shot 2020-08-17 at 3 35 35 AM
Screen Shot 2020-08-17 at 3 35 46 AM

It might be best to include some links back to Ubiquiti's help pages for the more advanced aspects of what other users might want/need/require.

-------

@scyto 
> Lastly this would still break in my environment. I found no workaround but to hardcode... is there something i am doing wrong?
> 
> image

For the `Network` keys, its my fault for not having updated those fields on my last push. I'm working on clearing up my `docker-compose.yml` and `.env` files. We are unable to use variables in the networking `key:` part of the yaml file. So that does have to be hard coded, which doesn't really hurt the portability of the files. 

--------

@scyto 
> did you give any thought to how we get folks to create the database - for example once the 3 containers are up can we run > docker-compose with the run command to create the database? I am still sitting here with no db created cause you didn't 
> give me instructions and i am being super literal and dumb ;-0 - lol.

I had not given this any thought when I submitted the pull request, up until I had to rebuild my Grafana stuff, as a test. 

As far as the documentation side of this goes, I was more going to lean upon you guys on, at the very least, writing out the directions on how to get into the CLI to perform these steps (there is a `docker-compose...` command way of doing this, along with getting into the Syno GUI to perform those commands). But, I'm thinking its probably best to try and automate this step as much as possible, which will require me to find that process. 

------------

> Most folks wont have a rendering callback url, and if they do, they should know how to set it up. I'd recommend removing those settings. The server domain setting is generally "fine" at the default and that should only need to be set in a custom configuration (where someone proxies through nginx, etc). These variables shouldn't be exposed by default. They can be there, but should be commented out.

I'll take these variable lines out.

**Comment by davidnewhall** [comment]
> That page does show 8443 is the correct port for every Unifi management service.

It's wrong. UDM/P listens on port 443. CloudKeys and other installations of the controller software listen on 8443. I personally default to 8443 because more people have "normal controllers" than folks with UDMs. I don't have any real concerns here other than to make sure both ports are listed as "something to try if the other port doesn't work."

I deal with people from all backgrounds and knowledge levels. Some folks that use this software are just starting out, and some have been administering networks for decades. I like to make sure the directions are useful for every level.

> As far as the documentation side of this goes, I was more going to lean upon you guys on, at the very least, writing out the directions on how to get into the CLI to perform these steps.

This document doesn't need to be perfect _right now_. We will certainly iterate and make it better as others provide feedback. I really appreciate you guys working on this though!

**Comment by jpartain89** [comment]
> > That page does show 8443 is the correct port for every Unifi management service.
> 
> It's wrong. UDM/P listens on port 443. CloudKeys and other installations of the controller software listen on 8443. I personally default to 8443 because more people have "normal controllers" than folks with UDMs. I don't have any real concerns here other than to make sure both ports are listed as "something to try if the other port doesn't work."

Of course... I have noticed over the past several months of having my Unifi hardware and what not, that the documentation isn't exactly kept fully updated all the time... 
 
> I deal with people from all backgrounds and knowledge levels. Some folks that use this software are just starting out, and some have been administering networks for decades. I like to make sure the directions are useful for every level.
> 
> > As far as the documentation side of this goes, I was more going to lean upon you guys on, at the very least, writing out the directions on how to get into the CLI to perform these steps.
> 
> This document doesn't need to be perfect _right now_. We will certainly iterate and make it better as others provide feedback. I really appreciate you guys working on this though!

And that does help quite a lot, allowing us to get the meat of everything setup and correct first, then making it look darn good after.

-------

For the database creation step, it appears that the influxdb team has that covered for us:

> Manually Initializing the Database
>
> To manually initialize the database and exit, the /init-influxdb.sh script can be used directly. It takes the same parameters as the influxd run command. As an example:
> 
> $ docker run --rm \
>       -e INFLUXDB_DB=db0 \
>       -e INFLUXDB_ADMIN_USER=admin -e INFLUXDB_ADMIN_PASSWORD=supersecretpassword \
>       -e INFLUXDB_USER=telegraf -e INFLUXDB_USER_PASSWORD=secretpassword \
>       -v $PWD:/var/lib/influxdb \
>       influxdb /init-influxdb.sh
> 
> The above would create the database db0, create an admin user with the password supersecretpassword, then create the telegraf user with your telegraf's secret password. It would then exit and leave behind any files it created in the volume that you **mounted.**

I'm thinking this will be the best bet, here.

**Comment by scyto** [comment]
@jpartain89 on the 8443 debate, i don't mind if it is in the file as 8443 or without a port - my point is just to document that there are two variants and reduce the number of github issues we will get opened :-)

**Comment by scyto** [comment]
@jpartain89 
nicely found, i think you are on the right track, theoretically we can use your env file to pass the env vars in and make the command smaller.  

Before i can think this through further i need someone to educate me - what is the entrypoint.sh script doing - i see there is an if statement for init-influxdb.sh - does this mean that script is being run at startup of a new container by default?  If it does then theoretically if we have all the env vars in the yaml it should initialize from them (note i have tried that but don't seem to have that working, so maybe the entrypoint.sh is doing something else?)  I continue to poke and hope at it this evening.

```
#!/bin/bash                                                                                                                                                  
set -e                                                                                                                                                       
                                                                                                                                                             
if [ "${1:0:1}" = '-' ]; then                                                                                                                                
    set -- influxd "$@"                                                                                                                                      
fi                                                                                                                                                           
                                                                                                                                                             
if [ "$1" = 'influxd' ]; then                                                                                                                                
        /init-influxdb.sh "${@:2}"                                                                                                                           
fi                                                                                                                                                           
                                                                                                                                                             
exec "$@"                
```

**Comment by scyto** [comment]
ok i answered my own question, yes that script run initi-influxdb.sh on first run

I have managed to make edits to the .env file and the yaml to initialize the database at first run of docker-compose up -d - how am i supposed to lint the pull request (if i install github, vscode etc can i do it there?)

**Comment by scyto** [comment]
this is my env file:

```
#influxdb
INFLUXDB_HTTP_AUTH_ENABLED=true
INFLUXDB_ADMIN_USER=admin
INFLUXDB_ADMIN_PASSWORD=<redacted>
INFLUXDB_DB=unifi
INFLUXDB_LOCAL_VOLUME=/volume1/docker/unifi-poller/influxdb
INFLUXDB_USER=unifi-poller
INFLUXDB_USER_PASSWORD=<redacted>

#grafana
GRAFANA_USERNAME=grafana
GRAFANA_PASSWORD=<redacted>
GRAFANA_NETWORK=Grafana_Net
GRAFANA_LOCAL_VOLUME=/volume1/docker/unifi-poller/grafana
GRAFANA_LOCAL_USERID=1031
GRAFANA_SERVER_DOMAIN=boards.url.com
GRAFANA_RENDERING_CALLBACK_URL=boards.url.com
GRAFANA_RENDERING_SERVER_URL=boards.url.com

#unifi-poller
POLLER_TAG=latest
POLLER_DEBUG=false
POLLER_SAVE_DPI=false
UNIFI_USER=unifi-poller
UNIFI_PASS=<redacted>
UNIFI_URL=https://192.168.1.1

**Comment by scyto** [comment]
this is my yml - this initalizes database correctly at docker compose up -d

Notes:

- I still have to hard code my networks on the last line - the variable version doesn't work, i don't know why?
- i added the lines for the admin and user passwords (i note the former was in the env file but not in here in the pull?)

```
# This is for unifi-poller v2.
version: '3'
services:

  influxdb:
    restart: always
    image: influxdb:latest
    volumes:
      - ${INFLUXDB_LOCAL_VOLUME}:/var/lib/influxdb
    environment:
      - INFLUXDB_DATA_DIR=/var/lib/influxdb/data
      - INFLUXDB_DATA_WAL_DIR=/var/lib/influxdb/wal
      - INFLUXDB_DATA_META_DIR=/var/lib/influxdb/meta
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_HTTP_AUTH_ENABLED=${INFLUXDB_HTTP_AUTH_ENABLED}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - INFLUXDB_USER=${INFLUXDB_USER}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD}
    networks:
      - ${GRAFANA_NETWORK}
  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ${GRAFANA_LOCAL_VOLUME}:/var/lib/grafana
    depends_on:
      - influxdb
    user: "${GRAFANA_LOCAL_USERID}"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_INSTALL_PLUGINS=grafana-clock-panel,natel-discrete-panel,grafana-piechart-panel
      - GF_SERVER_DOMAIN=${GRAFANA_SERVER_DOMAIN}
      - GF_ENFORCE_DOMAIN=true
      - GF_RENDERING_CALLBACK_URL=${GRAFANA_RENDERING_CALLBACK_URL}
      - GF_RENDERING_SERVER_URL=${GRAFANA_RENDERING_SERVER_URL}
    networks:
      - ${GRAFANA_NETWORK}
  unifi-poller:
    restart: always
    image: golift/unifi-poller:latest
    environment:
      - UP_INFLUXDB_USER=${INFLUXDB_ADMIN_USER}
      - UP_INFLUXDB_PASS=${INFLUXDB_ADMIN_PASSWORD}
      - UP_INFLUXDB_URL=http://influxdb:8086
      - UP_UNIFI_DEFAULT_USER=${UNIFI_USER}
      - UP_UNIFI_DEFAULT_PASS=${UNIFI_PASS}
      - UP_UNIFI_DEFAULT_URL=${UNIFI_URL}
      - UP_POLLER_DEBUG=${POLLER_DEBUG}
      - UP_UNIFI_DEFAULT_SAVE_DPI=${POLLER_SAVE_DPI}
    networks:
      - ${GRAFANA_NETWORK}
      
networks:
  Grafana_Net:

**Comment by scyto** [comment]
@jpartain89 was my granfana dashboard supposed to set itself up, or am i expected to do all that manually?
I note the 3 core plugins installed automatically.....

**Comment by scyto** [comment]
> @jpartain89 was my granfana dashboard supposed to set itself up, or am i expected to do all that manually?
> I note the 3 core plugins installed automatically.....

I guess not, i don't think this has to delay the pull being merged so long as if  in the doc for this compose we link folks to my section of configuring grafana or in the main docs (sorry havent looked at them in ages).

Then as v2 we can use this as a bradcrumb trail to figure out if there is easy way to configure folks default dashboard or not..... https://stackoverflow.com/questions/58166125/importing-datasource-and-grafana-dashboard-while-building-container

**Comment by scyto** [comment]
@davidnewhall  seems i may have spoken too soon.
I assume if I see this then poller is sure that it is writing to the influx database right?

```

2020/08/19 01:14:46 [INFO] UniFi Metrics Recorded. Sites: 1, Clients: 77, UAP: 8, USG/UDM: 1, USW: 9, IDS Events: 0, Points: 201, Fields: 5603, Errs: 0, Elapsed: 171ms | stdout
-- | --


```
I ask because when i configure grafana to look at the influxdb as a data source it tells me there  is no data....  not sure what i have done wrong.

**Comment by scyto** [comment]
@davidnewhall  there is no way to provision dashboards automagically from grafana.net so i logged a feature request https://github.com/grafana/grafana/issues/27059 will continue to explore the provision from disk option

**Comment by texasaggie97** [comment]
I just wanted to mention that I found the discussion on this issue helpful. 1) To get things set up on my Synology, and 2) to find the correct port for a UDM Pro.

**Comment by davidnewhall** [comment]
@scyto Feel free to clean up.

**Comment by scyto** [comment]
@davidnewhall will do, will try this weekend.

**Pull request merged**
